// <auto-generated />
using System;
using KarcagS.Common.Demo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KarcagS.Common.Demo.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20251225200121_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KarcagS.Common.Demo.DemoEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OtherGenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("OtherGenderId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("KarcagS.Common.Demo.GenderEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("KarcagS.Common.Demo.DemoEntry", b =>
                {
                    b.HasOne("KarcagS.Common.Demo.GenderEntry", "Gender")
                        .WithMany("Entries")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarcagS.Common.Demo.GenderEntry", "OtherGender")
                        .WithMany("OtherEntries")
                        .HasForeignKey("OtherGenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gender");

                    b.Navigation("OtherGender");
                });

            modelBuilder.Entity("KarcagS.Common.Demo.GenderEntry", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("OtherEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
